[package]
name = "ecdsa-example"
version = "0.1.0"
edition = "2021"

[dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
p256 = "0.13.2"
rand_core = { version = "0.6.4", features = ["getrandom"] }
